version: "3.9"

x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.2.1}
  env_file:
    - ${ENV_FILE_PATH:-.env}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET:-airflow_jwt_secret}
    AIRFLOW__API_AUTH__JWT_ISSUER: ${AIRFLOW__API_AUTH__JWT_ISSUER:-airflow}
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-great_expectations}
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/plugins:/opt/airflow/plugins
    - gx_docs:/app/gx_docs
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres-airflow:
      condition: service_healthy

services:

  app:
    image: pipeline_elt_glow
    build: .
    container_name: g6
    command: uv run main.py
    volumes:
      - gx_docs:/app/gx_docs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - database_network

  postgres:
    image: postgres:15
    container_name: glow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-glow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-glow1234}
      POSTGRES_DB: ${POSTGRES_DB:-glow_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-glow} -d ${POSTGRES_DB:-glow_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database_network
      - metabase_network

  postgres-airflow:
    image: postgres:16
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - airflow_network

  redis:
    image: redis:7.2-bookworm
    container_name: airflow_redis
    restart: always
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    networks:
      - airflow_network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    environment:
      MB_DB_FILE: /metabase-data/metabase
    volumes:
      - ./frontend/metabase_data:/metabase-data
    ports:
      - "3001:3000"
    networks:
      - metabase_network

  web-service:
    image: nginx:alpine
    container_name: static_gx
    volumes:
      - gx_docs:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
  
  elt-transformation:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: dbt
    working_dir: /usr/app/dbt_project
    entrypoint: /bin/sh -c "sleep infinity"
    env_file: .env
    volumes:
      - ./glow_dbt:/usr/app/dbt_project
      - ./profiles:/root/.dbt
    depends_on:
      - postgres
    networks:
      - database_network

  dbt-docs:
    image: nginx:alpine
    container_name: static_dbt
    volumes:
      - ./glow_dbt/target:/usr/share/nginx/html:ro
    ports:
      - "8181:80"

  # ===== AIRFLOW SERVICES =====

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    container_name: airflow_apiserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 150s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow_scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    container_name: airflow_dag_processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    container_name: airflow_worker
    healthcheck:
      test: ["CMD-SHELL", 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    container_name: airflow_triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow_init
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          export AIRFLOW_UID=$$(id -u)
        fi
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        mkdir -v -p /app/gx_docs
        
        /entrypoint airflow version
        /entrypoint airflow config list >/dev/null
        
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/
        chown -R "${AIRFLOW_UID}:0" /app/gx_docs
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    networks:
      - airflow_network

  flower:
    <<: *airflow-common
    command: celery flower
    container_name: airflow_flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow_network

volumes:
  postgres_data:
    name: "postgres_data"
    labels:
      description: "Volume persistente para PostgreSQL do Glow"

  postgres-airflow-db-volume:
    name: "postgres-airflow-db-volume"
    labels:
      description: "Volume persistente para PostgreSQL do Airflow"

  gx_docs:
    name: "gx_docs"
    labels:
      description: "Volume nomeado a ser compartilhado entre app (g6) e static_gx"

networks:
  database_network:
    driver: bridge
  metabase_network:
    driver: bridge
  airflow_network:
    driver: bridge