models:

  - name: mart_unified_products
    
    columns:
      
      - name: product_type
        tests: 
          - not_null
      
      - name: brand
        tests: 
          - not_null
          - dbt_utils.not_null_proportion:
              at_least: 0.95
              config:
                severity: warn

      - name: product_name
        tests: 
          - not_null

      - name: price
        tests:
          - not_null
    
    tests:
      
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_name
            - brand

      - dbt_utils.expression_is_true:
          expression: "price >= 0"


  - name: mart_sales

    columns:
      
      - name: country
        tests:
          - not_null

      - name: product
        tests:
          - not_null

      - name: price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: boxes_shipped
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0