glow_dbt:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: glow
      pass: glow1234
      port: 5432
      dbname: glow_db
      schema: silver
      threads: 4
  target: dev